# Use the official Python image as the base image
FROM python:3.13

# Set the working directory in the container
WORKDIR /app

# Copy the Python script to the container
COPY . .

# Define the command to run the application
CMD [ "python", "main.py" ]
